branch-defaults:
    master:
        environment: DraftkingsOptimizer-env-1
        group_suffix: null
environment-defaults:
    DraftkingsOptimizer-env-1:
        branch: null
        repository: null
    Draftkingsoptimizer-env-1:
        branch: null
        repository: null
global:
    application_name: draftkings-optimizer
    default_ec2_keyname: null
    default_platform:
        arn:aws:elasticbeanstalk:ca-central-1::platform/Node.js running
        on 64bit Amazon Linux/4.13.1
    default_region: ca-central-1
    include_git_submodules: true
    instance_profile: null
    platform_name: null
    platform_version: null
    profile: reformulary
    sc: git
    workspace_type: Application
